# Generated by Django 6.0.1 on 2026-01-26 13:17

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Устанавливается автоматически при обновлении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Отметка об удалении (мягкое удаление)', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время удаления', null=True, verbose_name='Дата удаления')),
                ('code', models.CharField(db_index=True, help_text='Введите код специальности в формате ХХ.ХХ.ХХ', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code_format', message='Код должен быть в формате "ХХ.ХХ.ХХ"', regex='^\\d{2}\\.\\d{2}\\.\\d{2}$')], verbose_name='Код специальности')),
                ('description', models.TextField(blank=True, help_text='Введите дополнительную информацию (необязательно)', null=True, verbose_name='Дополнительная информация')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при создании', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Полльзовательь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при обновлении', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Код специальности',
                'verbose_name_plural': 'Коды специальностей',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Устанавливается автоматически при обновлении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Отметка об удалении (мягкое удаление)', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время удаления', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(db_index=True, help_text='Введите название региона', max_length=100, unique=True, verbose_name='Название региона')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при создании', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Полльзовательь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при обновлении', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Устанавливается автоматически при обновлении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Отметка об удалении (мягкое удаление)', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время удаления', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(db_index=True, help_text='Введите название города', max_length=100, verbose_name='Название города')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при создании', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Полльзовательь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при обновлении', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('region', models.ForeignKey(help_text='Выберите регион', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='app.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Устанавливается автоматически при обновлении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Отметка об удалении (мягкое удаление)', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время удаления', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(db_index=True, help_text='Введите наименование специальности', max_length=100, verbose_name='Наименование спецаильности')),
                ('description', models.TextField(blank=True, help_text='Подробное описание специальности', null=True, verbose_name='Описание специальности')),
                ('is_active', models.BooleanField(default=True, help_text='Специальность активна для набора', verbose_name='Активна')),
                ('code', models.OneToOneField(help_text='Выберите код специальности', on_delete=django.db.models.deletion.PROTECT, related_name='speciality', to='app.codespeciality', verbose_name='Код специальности')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при создании', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Полльзовательь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при обновлении', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['code__code'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Устанавливается автоматически при обновлении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Отметка об удалении (мягкое удаление)', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время удаления', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(db_index=True, help_text='Введите наименование квалификации', max_length=50, verbose_name='Наименование квалификации')),
                ('based', models.CharField(choices=[('9', 'На базе 9 классов'), ('11', 'На базе 11 классов')], default='9', help_text='Выберите на базе скольки классов', max_length=2, verbose_name='На базе скольки классов')),
                ('duration_months', models.PositiveIntegerField(default=36, help_text='Введите срок обучения в месяцах (36 месяцев = 3 года)', validators=[django.core.validators.MinValueValidator(1, message='Срок обучения должен быть не менее 1 месяца'), django.core.validators.MaxValueValidator(120, message='Срок обучения должен быть не более 10 лет')], verbose_name='Срок обучения (в месяцах)')),
                ('description', models.TextField(blank=True, help_text='Введите дополнительную информацию (необязательно)', null=True, verbose_name='Дополнительная информация')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при создании', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Полльзовательь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при обновлении', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('speciality', models.ForeignKey(help_text='Выберите специальность', on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='app.speciality', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
                'ordering': ['speciality__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Устанавливается автоматически при обновлении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Отметка об удалении (мягкое удаление)', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время удаления', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(db_index=True, help_text='Введите название группы', max_length=10, unique=True, verbose_name='Название группы')),
                ('start_year', models.PositiveIntegerField(default=2026, help_text='Год начала обучения группы', verbose_name='Год начала обучения')),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Расчетный год окончания обучения', null=True, verbose_name='Год окончания обучения')),
                ('max_students', models.PositiveIntegerField(default=25, help_text='Максимальное количество студентов в группе', verbose_name='Максимальное количество студентов')),
                ('is_active', models.BooleanField(default=True, help_text='Группа активна и ведет обучение', verbose_name='Активная группа')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при создании', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Полльзовательь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при обновлении', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('qualification', models.ForeignKey(help_text='Выберите квалификацию', on_delete=django.db.models.deletion.PROTECT, to='app.qualification', verbose_name='Квалиифкация')),
                ('speciality', models.ForeignKey(help_text='Выберите специальность', on_delete=django.db.models.deletion.PROTECT, to='app.speciality', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Устанавливается автоматически при обновлении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Отметка об удалении (мягкое удаление)', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время удаления', null=True, verbose_name='Дата удаления')),
                ('lastname', models.CharField(db_index=True, help_text='Введите фамилию', max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(db_index=True, help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, help_text='Введите отчество', max_length=50, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона', max_length=128, region='RU', verbose_name='Телефон')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при создании', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Полльзовательь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено')),
                ('group', models.ForeignKey(help_text='Выберите группу', on_delete=django.db.models.deletion.PROTECT, to='app.group', verbose_name='Группа')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при обновлении', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('user', models.OneToOneField(help_text='Выберите пользователя', on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['name', 'lastname'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Устанавливается автоматически при обновлении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Отметка об удалении (мягкое удаление)', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время удаления', null=True, verbose_name='Дата удаления')),
                ('lastname', models.CharField(db_index=True, help_text='Введите фамилию', max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(db_index=True, help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, help_text='Введите отчество', max_length=50, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона', max_length=128, region='RU', verbose_name='Телефон')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при создании', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Полльзовательь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при обновлении', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('user', models.OneToOneField(help_text='Выберите пользователя', on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['lastname', 'name', 'middlename'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, help_text='Выберите куратора', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.teacher', verbose_name='Куратор'),
        ),
        migrations.AddIndex(
            model_name='codespeciality',
            index=models.Index(fields=['code'], name='app_codespe_code_202797_idx'),
        ),
        migrations.AddIndex(
            model_name='codespeciality',
            index=models.Index(fields=['is_deleted', 'code'], name='app_codespe_is_dele_202914_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['name'], name='app_region_name_ac32ce_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['is_deleted', 'name'], name='app_region_is_dele_08d726_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='app_city_name_d81496_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['region'], name='app_city_region__8a6060_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_deleted', 'name'], name='app_city_is_dele_d14a33_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_deleted', 'region'], name='app_city_is_dele_25f378_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'region')},
        ),
        migrations.AddIndex(
            model_name='speciality',
            index=models.Index(fields=['name'], name='app_special_name_4cc8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='speciality',
            index=models.Index(fields=['code'], name='app_special_code_id_2f159d_idx'),
        ),
        migrations.AddIndex(
            model_name='speciality',
            index=models.Index(fields=['is_active'], name='app_special_is_acti_16b4df_idx'),
        ),
        migrations.AddIndex(
            model_name='speciality',
            index=models.Index(fields=['is_deleted', 'is_active', 'name'], name='app_special_is_dele_d435d0_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['name'], name='app_qualifi_name_168093_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['speciality'], name='app_qualifi_special_9e701f_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['based'], name='app_qualifi_based_d790ee_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['is_deleted', 'speciality', 'based'], name='app_qualifi_is_dele_54d13e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together={('speciality', 'name', 'based')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='app_student_name_775569_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['lastname'], name='app_student_lastnam_0d75a9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user'], name='app_student_user_id_e4f7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_deleted', 'name', 'lastname', 'middlename'], name='app_student_is_dele_828855_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='app_teacher_name_c0b87f_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['lastname'], name='app_teacher_lastnam_a11045_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['user'], name='app_teacher_user_id_d9c2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_deleted', 'name', 'lastname', 'middlename'], name='app_teacher_is_dele_b69ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='app_group_name_91e977_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['speciality'], name='app_group_special_5ac885_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['qualification'], name='app_group_qualifi_4e9139_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['curator'], name='app_group_curator_e49556_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_active'], name='app_group_is_acti_5aad63_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['start_year'], name='app_group_start_y_e4fcfe_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_deleted', 'is_active', 'start_year'], name='app_group_is_dele_2a9e95_idx'),
        ),
    ]
