# Generated by Django 6.0.1 on 2026-01-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_city_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='codespeciality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматиески при создании', verbose_name='Дата создания'),
        ),
    ]
