# Generated by Django 6.0.1 on 2026-01-27 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_city_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматически при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='city',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Пользователь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено'),
        ),
        migrations.AlterField(
            model_name='codespeciality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматически при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='codespeciality',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Пользователь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматически при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='group',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Пользователь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматически при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Пользователь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматически при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='region',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Пользователь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматически при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Пользователь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматически при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='student',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Пользователь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматически при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Пользователь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено'),
        ),
    ]
