# Generated by Django 6.0.1 on 2026-01-29 18:03

import django.core.validators
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_city_created_at_alter_city_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Загрузите фотографию. Она будет автоматически сжата до 800x800 пикселей', null=True, upload_to='students/photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Фотография студента'),
        ),
    ]
