# Generated by Django 6.0.1 on 2026-01-29 19:26

import django.core.validators
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Загрузите фотографию. Она будет автоматически сжата до 800x800 пикселей', null=True, upload_to='students/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Фотография студента'),
        ),
    ]
