# Generated by Django 6.0.1 on 2026-01-30 10:40

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.OneToOneField(blank=True, help_text='Выберите город студента', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.city', verbose_name='Город студента'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Загрузите фотографию. Она будет автоматически сжата до 800x800 пикселей', null=True, upload_to='teachers/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Фотография преподавателя'),
        ),
    ]
