# Generated by Django 6.0.1 on 2026-01-30 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_city_alter_teacher_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматически при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Устанавливается автоматически при обновлении', verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Отметка об удалении (мягкое удаление)', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время удаления', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(help_text='Введите роль', max_length=30, unique=True, verbose_name='Роль')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при создании', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Пользователь удаливший запись', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Устанавливается автоматически при обновлении', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Выберите роль пользователя', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.role', verbose_name='Роль пользователя'),
        ),
    ]
